// 8.React/src/js/components/pc_header.js
import React from 'react'
import { BrowserRouter, Route, Link } from 'react-router-dom'
import { Row, Col, Menu, Icon, Tabs, message, Form, Input, Button, CheckBox, Modal } from 'antd'
const TabPane = Tabs.TabPane;
const FormItem = Form.Item
const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;

class PCHeader extends React.Component {
    constructor() {
        super();
        this.state = {
            current: 'top',
            modalVisible: false,
            action: 'login',
            hasLogined: false,
            userNickName: '',
            userid: 0
        };
    };

    componentWillMount() {
        if (localStorage.userid != '') {
            this.setState({ hasLogined: true });
            this.setState({ userNickName: localStorage.userNickName, userid: localStorage.userid });
        }
    };

    setModalVisible(value) {
        // 登录/注册 对话框
        this.setState({
            modalVisible: value
        })
    };

    handleClick(e) {
        // 菜单栏项目点击
        if (e.key == "register") {
            this.setState({
                current: 'register'
            });
            this.setModalVisible(true);
        } else {
            this.setState({
                current: e.key
            })
        }
    };

    handleSubmit(e) {
        // 页面开始向 API 进行提交数据
        e.preventDefault();
        var myFetchOptions = {
            method: 'GET'
        };
        var formData = this.props.form.getFieldsValue();   // Form自带方法, 获取该Form内全部组件的值
        console.log(formData);

        fetch("http://newsapi.gugujiankong.com/Handler.ashx?action=" + this.state.action + "&username=" + formData.userName + "&password=" + formData.password + "&r_userName=" + formData.r_userName + "&r_password=" + formData.r_password + "&r_confirmPassword=" + formData.r_confirmPassword, myFetchOptions)
            .then(response => response.json())
            .then(json => {
                this.setState({
                    userNickName: json.NickUserName,
                    userid: json.UserId
                });
                localStorage.userid = json.UserId;   // localStorage可以简单的存储一些JSON对象，便简易应用的数据存储
                localStorage.userNickName = json.NickUserName;
            });
            
        if (this.state.action == "login") {
            this.setState({ hasLogined: true });
        }
        message.success('请求成功!');
        this.setModalVisible(false);
    };

    callback(key) {
        if (key == 1) {
            this.setState({ action: 'login' });
        } else if (key == 2) {
            this.setState({ action: 'register' });
        }
    };

    logout() {
        localStorage.userid = '';
        localStorage.userNickName = '';
        this.setState({ hasLogined: false });
    };

    render() {
        let { getFieldProps } = this.props.form;

        const userShow = this.state.hasLogined
            ?
            <Menu.Item key="logout" className="register">
                <Button type="primary" htmlType="button">{this.state.userNickName}</Button>
                &nbsp;&nbsp;
                <Link to="/usercenter">
                    <Button type="dashed" htmlType="button">个人中心</Button>
                </Link>
                &nbsp;&nbsp;
                <Button type="ghost" htmlType="button" onClick={this.logout.bind(this)}>退出</Button>
            </Menu.Item>
            :
            <Menu.Item key="register" className="register">
                <Icon type="idcard"></Icon>注册/登录
            </Menu.Item>

        return (
            <header>
                <Row>
                    <Col span={2}></Col>
                    <Col span={4}>
                        <a href="/" className="logo">
                            <img src="/src/img/logo.png" alt="" />
                            <span>ReactNews</span>
                        </a>
                    </Col>
                    <Col span={16}>
                        <Menu
                            mode="horizontal"
                            onClick={this.handleClick.bind(this)}
                            selectedKeys={[this.state.current]}>
                            <Menu.Item key="top">
                                <Icon type="star" />头条
                            </Menu.Item>
                            <Menu.Item key="shehui">
                                <Icon type="usergroup-add" />社会
                            </Menu.Item>
                            <Menu.Item key="guonei">
                                <Icon type="lock" />国内
                            </Menu.Item>
                            <Menu.Item key="guoji">
                                <Icon type="global" />国际
                            </Menu.Item>
                            <Menu.Item key="yule">
                                <Icon type="smile-o" />娱乐
                            </Menu.Item>
                            <Menu.Item key="tiyu">
                                <Icon type="trophy" />体育
                            </Menu.Item>
                            <Menu.Item key="keji">
                                <Icon type="google" />科技
                            </Menu.Item>
                            <Menu.Item key="shishang">
                                <Icon type="gift" />时尚
                            </Menu.Item>
                            {userShow}
                        </Menu>

                        <Modal
                            title="用户中心"
                            wrapClassName="vartical-center-modal"
                            visible={this.state.modalVisible}
                            onCancel={() => this.setModalVisible(false)}
                            onOk={() => this.setModalVisible(false)}
                            okText="关闭">
                            <Tabs type="card" onChange={this.callback.bind(this)}>
                                <TabPane tab="登录" key="1">
                                    <Form horizontal onSubmit={this.handleSubmit.bind(this)}>
                                        <FormItem label="账户">
                                            <Input placeholder="请输入您的账号" {...getFieldProps('userName') } />
                                        </FormItem>
                                        <FormItem label="密码">
                                            <Input type="password" placeholder="请输入您的密码" {...getFieldProps('password') } />
                                        </FormItem>
                                        <Button type="primary" htmlType="submit">登录</Button>
                                    </Form>
                                </TabPane>
                                <TabPane tab="注册" key="2">
                                    <Form horizontal="true" onSubmit={this.handleSubmit.bind(this)}>
                                        <FormItem label="账户">
                                            <Input placeholder="请输入您的账户" {...getFieldProps('r_userName') } />
                                        </FormItem>
                                        <FormItem label="密码">
                                            <Input type="password" placeholder="请输入您的密码" {...getFieldProps('r_password') } />
                                        </FormItem>
                                        <FormItem label="确认密码">
                                            <Input type="password" placeholder="请再次输入您的密码" {...getFieldProps('r_confirmPassword') } />
                                        </FormItem>
                                        <Button type="primary" htmlType="submit">注册</Button>
                                    </Form>
                                </TabPane>
                            </Tabs>
                        </Modal>

                    </Col>
                    <Col span={2}></Col>
                </Row>
            </header>
        )
    }
}

export default PCHeader = Form.create({})(PCHeader);

// 9.Vue/src/components/common/pc_header.vue
<template>
    <div class="header">
        <el-row>
            <el-col :span="2" >&nbsp;</el-col>

            <el-col :span="20" >
                <el-row>
                    <el-col :span="5" >
                        <div class="logo">
                            <img src="../../assets/logo.png" alt="">
                            <router-link to="/">
                                <span>VueNews</span>
                            </router-link>
                        </div>
                    </el-col>
                    <el-col :span="19" >
                        <el-menu
                            :default-active="activeNav"
                            active-text-color="#41B883"
                            mode="horizontal" >
                            <el-menu-item index="1" >
                                <i class="el-icon-star-on"></i>
                                头条
                            </el-menu-item>
                            <el-menu-item index="2" >
                                <i class="el-icon-phone"></i>
                                社会
                            </el-menu-item>
                            <el-menu-item index="3" >
                                <i class="el-icon-zoom-out"></i>
                                国内
                            </el-menu-item>
                            <el-menu-item index="4" >
                                <i class="el-icon-zoom-in"></i>
                                国际
                            </el-menu-item>
                            <el-menu-item index="5" >
                                <i class="el-icon-service"></i>
                                娱乐
                            </el-menu-item>
                            <el-menu-item index="6" >
                                <i class="el-icon-share"></i>
                                体育
                            </el-menu-item>
                            <el-menu-item index="7" >
                                <i class="el-icon-upload"></i>
                                科技
                            </el-menu-item>
                            <el-menu-item index="8" >
                                <i class="el-icon-sold-out"></i>
                                时尚
                            </el-menu-item>
                            <el-menu-item index="user" class="register" v-if="isLogined" >
                                <el-button type="priamry">{{ $store.state.username }}</el-button>
                                <router-link to="/usercenter">
                                    <el-button type="priamry" plain>个人中心</el-button>
                                </router-link>
                                <el-button @click="logout">退出</el-button>
                            </el-menu-item>
                            <el-menu-item index="reg" class="register" v-else >
                                <p @click="dialogOn">
                                    <i class="el-icon-info"></i>
                                    登录/注册
                                </p>
                            </el-menu-item>
                            <el-dialog title="用户中心" :modal="true" :visible.sync="showDialog" width="315px" >
                                <el-tabs v-model="activeReg" type="card" >
                                    <el-tab-pane label="登录" name="login" >
                                        <el-form :model="loginForm" :rules="rulesForm" status-icon >
                                            <el-form-item label="账户 :" prop="username" >
                                                <el-input v-model="loginForm.username"></el-input>
                                            </el-form-item>
                                            <el-form-item label="密码 :" prop="password" >
                                                <el-input type="password" v-model="loginForm.password"></el-input>
                                            </el-form-item>
                                            <el-form-item>
                                                <el-button type="primary" @click="submitForm('loginForm')" class="submitButton" >登录</el-button>
                                            </el-form-item>
                                        </el-form>
                                    </el-tab-pane>
                                    <el-tab-pane label="注册" name="register" >
                                        <el-form :model="regForm" :rules="rulesForm" status-icon >
                                            <el-form-item label="账户 :" prop="username" >
                                                <el-input v-model="regForm.username"></el-input>
                                            </el-form-item>
                                            <el-form-item label="密码 :" prop="password" >
                                                <el-input type="password" v-model="regForm.password"></el-input>
                                            </el-form-item>
                                            <el-form-item label="确认密码 :" prop="confirmPassword" >
                                                <el-input type="password" v-model="regForm.confirmPassword"></el-input>
                                            </el-form-item>
                                            <el-form-item>
                                                <el-button type="primary" @click="submitForm('regForm')" class="submitButton" >注册</el-button>
                                            </el-form-item>
                                        </el-form>
                                    </el-tab-pane>
                                </el-tabs>
                            </el-dialog>
                        </el-menu>
                    </el-col>
                </el-row>
            </el-col>

            <el-col :span="2" ></el-col>
        </el-row>
    </div>
</template>

<script>
import axios from 'axios'
import store from '@/vuex/store'
import { mapState, mapMutations } from 'vuex';

export default {
  name: "pc_header",
  data() {

    // 表单验证逻辑
    var validateUsername = (rule, value, callback) => {
      if (value === "") {
        callback(new Error("请输入用户名"));
      } else {
        if (value > 2 || value < 10) {
            callback(new Error("用户名的长度必须在2~10"));
          } else {
            callback();
          }
      }
    };
    var validatePassword = (rule, value, callback) => {
      if (value === "") {
        callback(new Error("请输入用密码"));
      } else {
        callback();
      }
    };
    var validateConfirmPassword = (rule, value, callback) => {
      if (value === "") {
        callback(new Error("请再次输入密码"));
      } else if (value !== this.regForm.password) {
        callback(new Error("两次输入密码不一致!"));
      } else {
        callback();
      }
    };

    return {
      activeNav: "1",
      showDialog: false,
      activeReg: "login",
      // 登录表单的各项值
      loginForm: {
        username: "",
        password: ""
      },
      // 注册表单的各项值
      regForm: {
        username: "",
        password: "",
        confirmPassword: ''
      },
      // 表单验证数据
      rulesForm: {
        username: [{ validator: validateUsername, trigger: "blur" }],
        password: [{ validator: validatePassword, trigger: "blur" }],
        confirmPassword: [{ validator: validateConfirmPassword, trigger: "blur" }]
      },
      // 用户名 ID 初始值
      userNickName: '',
      userId: 0,
      // 是否已登录
      isLogined: false
    };

  },
  store,
  computed: {
      ...mapState(['username', 'userid'])
  },
  methods: {

      ...mapMutations(['changUsername', 'changUserid']),

    dialogOn() {
      this.showDialog = true;
    },

    submitForm(formName) {
      axios("http://newsapi.gugujiankong.com/Handler.ashx?action=" + this.activeReg + "&username=" + this.loginForm.username + "&password=" + this.loginForm.password + "&r_userName=" + this.regForm.username + "&r_password=" + this.regForm.password + "&r_confirmPassword=" + this.regForm.confirmPassword)
        .then(response => {
          this.$store.commit('changUsername', response.data.NickUserName);
          this.$store.commit('changUserid', response.data.UserId);
        });

      this.isLogined = true;
      this.showDialog = false;
      this.$message({
          message: '恭喜你，这是一条成功消息',
          type: 'success'
      });
    },

    logout() {
      this.isLogined = false;
      this.$store.commit('changUsername', '');
      this.$store.commit('changUserid', 0);
    }
  }

};
</script>

<style>
.header {
  width: 100%; height: 48px;
  margin-bottom: 40px;
}
.header a:hover{
    text-decoration: none;
}

.logo img {
  width: 60px;
  height: 60px;
  float: left;
}
.logo span {
  height: 60px;
  padding-left: 8px;
  font-size: 26px;
  line-height: 60px;
  color: #41b883;
}

.register {
  float: right !important;
}
.submitButton {
  margin-top: 20px;
}

.el-button--primary{
    background: #41b883 !important;
}
.el-button--primary:active{
    background: #3de499 !important;
}
</style>
