// 9.Vue/src/components/page/pc_newscontainer.vue
<template>
    <div>
        <el-row>
            <el-col :span="2">&nbsp;</el-col>

            <el-col :span="20">
                <el-row>
                  <el-col :span="8">
                      <div class="carousel">
                          <el-carousel trigger="click">
                              <el-carousel-item v-for="item of 4" :key="item"></el-carousel-item>
                          </el-carousel>
                      </div>
                      <div class="pc-news-img-block">
                          <PCNewsImgBlock count="6" type="top" singleWidth="32%" newsMargin="threeColNews" cardTitle="国际头条"></PCNewsImgBlock>
                      </div>
                  </el-col>
                  <el-col :span="8">
                      <div class="pc-news-block">
                          <el-tabs v-model="activeTab">
                              <el-tab-pane label=""></el-tab-pane>
                              <el-tab-pane label=""></el-tab-pane>
                              <el-tab-pane label=""></el-tab-pane>
                              <el-tab-pane label="头条" name="top">
                                  <PCNewsBlock count="22" type="top"></PCNewsBlock>
                              </el-tab-pane>
                              <el-tab-pane label=""></el-tab-pane>
                              <el-tab-pane label="国际" name="guoji">
                                  <PCNewsBlock count="22" type="guoji"></PCNewsBlock>
                              </el-tab-pane>
                              <el-tab-pane label=""></el-tab-pane>
                              <el-tab-pane label="娱乐" name="yule">
                                  <PCNewsBlock count="22" type="yule"></PCNewsBlock>
                              </el-tab-pane>
                          </el-tabs>
                      </div>
                  </el-col>
                  <el-col :span="8">
                      <el-tabs class="wangyi" v-model="productTab">
                        <el-tab-pane label=""></el-tab-pane>
                        <el-tab-pane label=""></el-tab-pane>
                        <el-tab-pane label=""></el-tab-pane>
                        <el-tab-pane label=""></el-tab-pane>
                        <el-tab-pane label=""></el-tab-pane>
                        <el-tab-pane label="网易产品" name="wangyi">
                            <PCProduct></PCProduct>
                        </el-tab-pane>
                      </el-tabs>
                  </el-col>
                </el-row>
                <PCNewsImgBlock count="10" type="guonei" singleWidth="9.4%" newsMargin="oneLineNews" cardTitle="国内新闻"></PCNewsImgBlock>
                <PCNewsImgBlock count="20" type="yule" singleWidth="9.4%" newsMargin="twoLineNews" cardTitle="娱乐新闻"></PCNewsImgBlock>
            </el-col>

            <el-col :span="2"></el-col>
        </el-row>

        
    </div>
</template>

<script>
import PCNewsBlock from "@/components/page/pc_news_block";
import PCNewsImgBlock from "@/components/page/pc_news_img_block";
import PCProduct from '@/components/page/pc_product'

export default {
  name: "pc_newscontainer",
  data() {
    return {
      activeTab: "top",
      productTab: 'wangyi'
    };
  },
  components: {
    PCNewsBlock,
    PCNewsImgBlock,
    PCProduct
  }
};
</script>

<style>
.carousel,
.pc-news-img-block {
  width: 95%;
}
/* 图片轮播 */
.el-carousel__item {
  background-size: 100% 100%;
}
.el-carousel__item:nth-of-type(1) {
  background-image: url(../../assets/carousel_1.jpg);
}
.el-carousel__item:nth-of-type(2) {
  background-image: url(../../assets/carousel_2.jpg);
}
.el-carousel__item:nth-of-type(3) {
  background-image: url(../../assets/carousel_3.jpg);
}
.el-carousel__item:nth-of-type(4) {
  background-image: url(../../assets/carousel_4.jpg);
}

.wangyi {
    margin-left: 30px;
}
</style>

// 8.React/src/js/components/pc_newscontainer.js
import React from 'react'
import { Row, Col, Tabs, Carousel } from 'antd'
const TabPane = Tabs.TabPane
import PCNewsBlock from './pc_news_block'
import PCNewsImageBlock from './pc_news_image_block'
import PCProduct from './pc_product'

export default class PCNewsContainer extends React.Component {
    render() {
        const settings = {
            dots: true,
            infinite: true,
            speed: 1000,
            slidesToShow: 1,
            autoplay: true
        };

        const imageblock2 = document.body.clientWidth*5/6;   // js实现自适应布局

        return (
            <div>
                <Row>
                    <Col span={2}></Col>

                    <Col span={20} className="container">
                        {/* 左边轮播图 */}
                        <div className="leftContainer">
                            <div className="carousel">
                                <Carousel {...settings}>
                                    <div><img src="/src/img/carousel_1.jpg" alt="" /></div>
                                    <div><img src="/src/img/carousel_2.jpg" alt="" /></div>
                                    <div><img src="/src/img/carousel_3.jpg" alt="" /></div>
                                    <div><img src="/src/img/carousel_4.jpg" alt="" /></div>
                                </Carousel>
                            </div>
                            <PCNewsImageBlock count={6} type="guoji" width="401px" cartTitle="国际头条" imageWidth="112px" />
                        </div>
                        {/* 中部选项卡新闻 */}
                        <Tabs className="tabs_news">
                            <TabPane tab="头条" key="1">
                                <PCNewsBlock count={22} type="top" width="100%" />
                            </TabPane>
                            <TabPane tab="国际" key="2">
                                <PCNewsBlock count={22} type="guoji" width="100%" />
                            </TabPane>
                            <TabPane tab="娱乐" key="3">
                                <PCNewsBlock count={22} type="yule" width="100%" />
                            </TabPane>
                        </Tabs>
                        {/* 网易产品模块HTML */}
                        <Tabs className="tabs_product" style={{marginLeft:"20px"}}>
                            <TabPane tab="React News 产品" key="1">
                                <PCProduct />
                            </TabPane>
                        </Tabs>
                        {/* 两行图片新闻 */}
                        <div>
                            <PCNewsImageBlock count={10} type="guonei" width="100%" cartTitle="国内新闻" imageWidth="118px" />
                            <PCNewsImageBlock count={20} type="yule" width="100%" cartTitle="娱乐新闻" imageWidth="118px" />
                        </div>
                    </Col>

                    <Col span={2}></Col>
                </Row>
            </div>
        )
    }
};
